# Generated by Django 5.0.1 on 2024-01-12 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Название')),
                ('district', models.CharField(choices=[('ВМР', 'Витаминкомбинат'), ('ГМР', 'Гидростроителей'), ('ЗИП', 'Завод измерительных приборов'), ('КМР', 'Комсомольский'), ('ПМР', 'Пашковский'), ('СМР', 'Славянский'), ('ЧМР', 'Черемушки'), ('ЮМР', 'Юбилейный'), ('ФМР', 'Фестивальный'), ('ЦМР', 'Центральный')], max_length=4, verbose_name='Район')),
                ('street', models.CharField(max_length=32, verbose_name='Улица')),
                ('number', models.CharField(max_length=8, verbose_name='Номер дома')),
                ('gis_link', models.CharField(max_length=128, verbose_name='Ссылка на 2gis')),
            ],
            options={
                'verbose_name': 'Автовокзал',
                'verbose_name_plural': 'Автовокзалы',
            },
        ),
        migrations.CreateModel(
            name='To',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=32, verbose_name='Куда')),
            ],
            options={
                'verbose_name': 'Направление из Краснодара',
                'verbose_name_plural': 'Направления из Краснодара',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=11, verbose_name='Номер телефона')),
                ('description', models.TextField(verbose_name='Описание')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.busstation', verbose_name='Автовокзал')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_dt', models.DateTimeField(verbose_name='Время начала поездки')),
                ('end_dt', models.DateTimeField(verbose_name='Время конца поездки')),
                ('ticket_price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Цена билета (руб.)')),
                ('ticket_count', models.PositiveIntegerField(verbose_name='Количество билетов')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.busstation', verbose_name='Станция')),
                ('to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.to', verbose_name='Куда')),
            ],
            options={
                'verbose_name': 'Поездка',
                'verbose_name_plural': 'Поездки',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owned', models.BooleanField(default=False, verbose_name='Занят')),
                ('place', models.PositiveIntegerField(verbose_name='Место')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.trip', verbose_name='Поездка')),
            ],
            options={
                'verbose_name': 'Билет',
                'verbose_name_plural': 'Билеты',
                'unique_together': {('trip', 'place')},
            },
        ),
    ]
