# Generated by Django 5.0.1 on 2024-01-21 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0002_purchase_done_alter_purchase_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default=0, max_length=300, upload_to='', verbose_name='Картинка'),
            preserve_default=False,
        ),
    ]
