# Generated by Django 5.0.1 on 2024-01-21 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0003_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cost',
            field=models.PositiveIntegerField(verbose_name='Цена'),
        ),
    ]
