# Generated by Django 5.0.1 on 2024-01-21 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0004_alter_product_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата сделки'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='done',
            field=models.BooleanField(default=False, verbose_name='Состояние'),
        ),
    ]
