# Generated by Django 5.0.1 on 2024-01-21 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0005_alter_purchase_datetime_alter_purchase_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='done',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Состояние'),
        ),
    ]
