# Generated by Django 5.0.1 on 2024-01-21 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0006_alter_purchase_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='done',
            field=models.BooleanField(default=False, verbose_name='Состояние'),
        ),
    ]
