from .index_view import IndexView
from .login_view import LoginView
from .logout_view import LogoutView
from .register_view import RegisterView
from .create_storage_view import CreateStorageView
from .edit_storage_view import EditStorageView
from .delete_storage_view import DeleteStorageView
from .create_product_view import CreateProductView
from .product_count_view import ProductCountView
from .delete_product_view import DeleteProductView
from .edit_product_view import EditProductView
