# Generated by Django 5.0.1 on 2024-01-18 12:27

import calculator.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0003_alter_position_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='salary',
            field=calculator.models.MoneyField(blank=True, decimal_places=2, max_digits=19, null=True, verbose_name='Надбавка сотрудника'),
        ),
    ]
