# Generated by Django 5.0.1 on 2024-01-18 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0006_position_work_days_alter_defaulttaxes_pensionary_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='work_days',
        ),
    ]
