# Generated by Django 5.0.1 on 2024-01-18 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0007_remove_position_work_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='calculator.position', verbose_name='Должность'),
            preserve_default=False,
        ),
    ]
