# Generated by Django 5.0.4 on 2024-05-05 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmshow',
            name='datetime',
            field=models.DateTimeField(verbose_name='Время показа'),
        ),
    ]
