# Generated by Django 5.0.4 on 2024-05-05 15:57

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_filmshow_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 5, 15, 57, 21, 956861, tzinfo=datetime.timezone.utc), verbose_name='Дата приобретения'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='filmshow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.filmshow', verbose_name='Сеанс'),
        ),
    ]
