# Generated by Django 5.0.1 on 2024-01-15 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(verbose_name='Ссылка на статью')),
                ('main_photo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фото')),
                ('title', models.CharField(max_length=100, verbose_name='Название статьи')),
                ('preview', models.CharField(max_length=100, verbose_name='Превью')),
                ('content', models.TextField(verbose_name='Контент')),
                ('create', models.DateTimeField(auto_now_add=True, verbose_name='Написана')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
            },
        ),
    ]
