# Generated by Django 5.0.1 on 2024-01-15 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='preview',
            field=models.CharField(max_length=300, verbose_name='Превью'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=300, verbose_name='Название статьи'),
        ),
    ]
