# Generated by Django 5.0.1 on 2024-01-16 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_article_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='main_photo',
            field=models.ImageField(blank=True, max_length=300, null=True, upload_to='', verbose_name='Фото'),
        ),
    ]
