# Generated by Django 5.0.1 on 2024-01-04 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankBrunch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Обязательное поле. Не более 60 символов.', max_length=60, verbose_name='Название филиала')),
                ('administrator', models.OneToOneField(help_text='Администратор отвечает за создание обслуживающих талонов.', on_delete=django.db.models.deletion.CASCADE, to='main_app.user', verbose_name='Администратор')),
            ],
            options={
                'verbose_name': 'Филиалы',
            },
        ),
    ]
