# Generated by Django 5.0.1 on 2024-01-04 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_bankbrunch'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bankbrunch',
            options={'verbose_name': 'Филиал', 'verbose_name_plural': 'Филиалы'},
        ),
        migrations.AlterField(
            model_name='bankbrunch',
            name='administrator',
            field=models.OneToOneField(error_messages={'unique': 'Данный администратор уже отвечает за один филиал.'}, help_text='Администратор отвечает за создание обслуживающих талонов.', on_delete=django.db.models.deletion.CASCADE, to='main_app.user', verbose_name='Администратор'),
        ),
    ]
