# Generated by Django 5.0.1 on 2024-01-04 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_bankbrunch_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brunch', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.bankbrunch', verbose_name='Филиал')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main_app.user', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
    ]
