# Generated by Django 5.0.1 on 2024-01-04 21:55

import django.db.models.deletion
import main_app.models.employee
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main_app.user', validators=[main_app.models.employee.cant_be_administrator], verbose_name='Пользователь'),
        ),
    ]
