# Generated by Django 5.0.1 on 2024-01-06 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_serviceticket'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serviceticket',
            options={'verbose_name': 'Обслуживаемый талон', 'verbose_name_plural': 'Обслуживаемые талоны'},
        ),
        migrations.AddField(
            model_name='serviceticket',
            name='client',
            field=models.CharField(default=1, max_length=100, verbose_name='ФИО клиента'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='serviceticket',
            name='employee',
            field=models.OneToOneField(blank=True, help_text='Вы можете сразу назначить сотрудника, обойдя очередь обслуживания.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.employee', verbose_name='Ответственный сотрудник'),
        ),
    ]
