# Generated by Django 5.0.1 on 2024-01-06 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_serviceticket_options_serviceticket_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceticket',
            name='brunch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.bankbrunch', verbose_name='Филиал'),
            preserve_default=False,
        ),
    ]
