# Generated by Django 5.0.1 on 2024-01-06 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_serviceticket_brunch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceticket',
            name='employee',
            field=models.OneToOneField(default=1, help_text='Вы можете сразу назначить сотрудника, обойдя очередь обслуживания.', on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.employee', verbose_name='Ответственный сотрудник'),
            preserve_default=False,
        ),
    ]
