# Generated by Django 5.0.1 on 2024-01-11 10:42

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_fullname', models.CharField(max_length=128, verbose_name='Отправитель')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Контент')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('modified', models.DateTimeField(blank=True, null=True, verbose_name='Изменен')),
                ('score', models.IntegerField(default=0, verbose_name='Оценка')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
            },
        ),
    ]
