# Generated by Django 5.0.1 on 2024-01-11 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_remove_post_user_fullname_post_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='post',
            name='score',
        ),
    ]
