name: s7_ais_cw
description: 'A new Flutter project.'
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.2

dependencies:
  archive: ^3.3.0
  docx_template: ^0.4.0
  dropdown_search: ^6.0.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^1.2.2
  intl: ^0.19.0
  open_file: ^3.5.10
  path: ^1.9.0
  path_provider: ^2.1.5

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/osago_tpl.docx
    - assets/coefficients.json
