name: s7_md_lw_15
description: 'A new Flutter project.'
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^6.1.0
  video_player: ^2.9.2
  path: ^1.9.0
  file_picker: ^8.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/samples/
    - assets/music/
    - assets/videos/
