# Generated by Django 5.0.1 on 2024-01-03 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklad_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'unique': 'Данный адрес электронной почты уже занят.'}, max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
