# Generated by Django 5.0.1 on 2024-01-03 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklad_app', '0003_storage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='description',
            field=models.TextField(blank=True, help_text='При необходимости, вы можете указать дополнительную информацию', max_length=80, null=True, verbose_name='Описание'),
        ),
    ]
