# Generated by Django 5.0.1 on 2024-01-03 22:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklad_app', '0005_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterField(
            model_name='product',
            name='count',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(limit_value=0)], verbose_name='Количество'),
        ),
    ]
