# Generated by Django 5.0.1 on 2024-01-03 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sklad_app', '0006_alter_product_options_alter_product_count'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('vendor_code', 'storage')},
        ),
    ]
