# Generated by Django 5.0.1 on 2024-01-18 12:16

import calculator.models
import django.db.models.deletion
import month.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('salary', calculator.models.MoneyField(decimal_places=2, max_digits=19, verbose_name='Надбавка сотрудника')),
            ],
            options={
                'verbose_name': 'Предприятие',
                'verbose_name_plural': 'Предприятия',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('salary', calculator.models.MoneyField(decimal_places=2, max_digits=19, verbose_name='Зарплата за должность')),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должности',
            },
        ),
        migrations.CreateModel(
            name='Bonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', month.models.MonthField(verbose_name='Месяц')),
                ('type', models.CharField(choices=[('Процентная', 'Процентная'), ('Сумма', 'Сумма')], max_length=20, verbose_name='Тип')),
                ('value', calculator.models.MoneyField(decimal_places=2, max_digits=19, verbose_name='Значение')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculator.employee', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Премия',
                'verbose_name_plural': 'Премии',
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='calculator.position', verbose_name='Должность'),
        ),
    ]
