# Generated by Django 5.0.1 on 2024-01-18 12:23

import calculator.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bonus',
            options={'verbose_name': 'Надбавка/Штраф', 'verbose_name_plural': 'Надбавки/Штрафы'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Сотрудник', 'verbose_name_plural': 'Сотрудники'},
        ),
        migrations.AlterField(
            model_name='bonus',
            name='value',
            field=calculator.models.BonusField(decimal_places=2, help_text='Вы можете ввести отрицательное значения для штрафа', max_digits=19, verbose_name='Значение'),
        ),
    ]
