# Generated by Django 5.0.1 on 2024-01-18 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0004_alter_employee_salary'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultTaxes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_singleton', models.BooleanField(default=True, editable=False, unique=True)),
                ('personal', models.PositiveIntegerField(default=13, max_length=2, verbose_name='НДФЛ')),
                ('pensionary', models.PositiveIntegerField(default=22, max_length=2, verbose_name='Пенсионные отчисления')),
            ],
            options={
                'verbose_name': 'Налоги',
                'verbose_name_plural': 'Налоги',
            },
        ),
        migrations.RemoveField(
            model_name='bonus',
            name='month',
        ),
    ]
