# Generated by Django 5.0.1 on 2024-01-18 21:24

import calculator.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0005_defaulttaxes_remove_bonus_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='work_days',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(limit_value=30, message='Количество пропусков в месяц не может превышать 31 дня.')], verbose_name='Рабочих дней в месяц (30 дн.)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='defaulttaxes',
            name='pensionary',
            field=models.PositiveIntegerField(default=22, validators=[django.core.validators.MaxValueValidator(limit_value=100, message='Проценты не могут превышать сотни.')], verbose_name='Пенсионные отчисления'),
        ),
        migrations.AlterField(
            model_name='defaulttaxes',
            name='personal',
            field=models.PositiveIntegerField(default=13, validators=[django.core.validators.MaxValueValidator(limit_value=100, message='Проценты не могут превышать сотни.')], verbose_name='НДФЛ'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='salary',
            field=calculator.models.MoneyField(blank=True, decimal_places=2, default=0, max_digits=19, null=True, verbose_name='Индивидуальная надбавка'),
        ),
        migrations.AlterField(
            model_name='position',
            name='salary',
            field=calculator.models.MoneyField(decimal_places=2, max_digits=19, verbose_name='Заработная ставка (за месяц)'),
        ),
    ]
