# Generated by Django 5.0.1 on 2024-01-19 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0011_alter_employee_first_name_alter_employee_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='description',
        ),
    ]
