name: s7_md_lw_05_to_06
description: 'A new Flutter project.'
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.3.2
  adaptive_theme: ^3.6.0
  flutter_local_notifications: ^18.0.1
  collection: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/smile-nice.png
