name: s8_dmss_cw
description: 'A new Flutter project.'
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  flutter_expandable_fab: ^2.4.1
  intl: ^0.19.0
  firebase_core: ^3.10.1
  firebase_core_web: ^2.21.1
  firebase_auth: ^5.4.2
  cloud_firestore: ^5.6.5
  go_router: ^14.8.0
  provider: ^6.1.2
  adaptive_theme: ^3.6.0
  expandable: ^5.0.1
  animated_reorderable_list: ^1.2.0
  slide_countdown: ^2.0.2
  email_validator: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
