dictionary = {
    'Цветы ириса': {
        'sepal length (cm)': 'Длина чашелистика (см)',
        'sepal width (cm)': 'Ширина чашелистика (см)',
        'petal length (cm)': 'Длина лепестка (см)',
        'petal width (cm)': 'Ширина лепестка (см)',
        'class': 'Класс'
    },
    'Рак молочной железы': {
        'mean radius': 'Средний радиус',
        'mean texture': 'Средняя текстура',
        'mean perimeter': 'Средний периметр',
        'mean area': 'Средняя площадь',
        'mean smoothness': 'Средняя гладкость',
        'mean compactness': 'Средняя компактность',
        'mean concavity': 'Средняя выпуклость',
        'mean concave points': 'Средние точки выпуклости',
        'mean symmetry': 'Средняя симметрия',
        'mean fractal dimension': 'Средняя фрактальная размерность',
        'radius error': 'Погрешность радиуса',
        'texture error': 'Погрешность текстуры',
        'perimeter error': 'Погрешность периметра',
        'area error': 'Погрешность площади',
        'smoothness error': 'Погрешность гладкости',
        'compactness error': 'Погрешность компактности',
        'concavity error': 'Погрешность выпуклости',
        'concave points error': 'Погрешность точек выпуклости',
        'symmetry error': 'Погрешность симметрии',
        'fractal dimension error': 'Погрешность фрактальной размерности',
        'worst radius': 'Наибольший радиус',
        'worst texture': 'Наихудшая текстура',
        'worst perimeter': 'Наибольший периметр',
        'worst area': 'Наибольшая площадь',
        'worst smoothness': 'Наихудшая гладкость',
        'worst compactness': 'Наихудшая компактность',
        'worst concavity': 'Наихудшая выпуклость',
        'worst concave points': 'Наихудшие точки выпуклости',
        'worst symmetry': 'Наихудшая симметрия',
        'worst fractal dimension': 'Наихудшая фрактальная размерность',
        'class': 'Класс'
    },
    'Сорта вин': {
        'alcohol': 'Алкоголь',
        'malic_acid': 'Яблочная кислота',
        'ash': 'Зола',
        'alcalinity_of_ash': 'Щелочность золы',
        'magnesium': 'Магний',
        'total_phenols': 'Всего фенола',
        'flavanoids': 'Флаваноиды',
        'nonflavanoid_phenols': 'Нефлаваноидные фенолы',
        'proanthocyanins': 'Проантоцианины',
        'color_intensity': 'Интенсивность цвета',
        'hue': 'Оттенок',
        'od280/od315_of_diluted_wines': 'OD280/OD315 разбавленных вин',
        'proline': 'Пролин',
        'class': 'Класс'
    }
}
