import 'package:s7_ais_cw/osago/template.dart';

Map<String, dynamic> testData = {
  'ins_fullname': 'Муссова Оксана Сафарбиевна',
  'ins_birthday': '21.12.1979',
  'ins_doc_type': 'Паспорт',
  'ins_doc_series': '91 08',
  'ins_doc_number': '529244',
  'ins_addr_index': '350080',
  'ins_addr_federal': 'Россия, Краснодарский край',
  'ins_addr_district': '',
  'ins_addr_location': 'Краснодар',
  'ins_addr_street': 'Тюляева',
  'ins_addr_house': '25',
  'ins_addr_building': '',
  'ins_addr_apart': '90',
  'ins_phone': '+79181385188',
  'ins_shortname': 'Муссова О. С.',
  'act_fdt_day': '15',
  'act_fdt_month': 'декабря',
  'act_fdt_year': '24',
  'act_tdt_day': '15',
  'act_tdt_month': 'марта',
  'act_tdt_year': '25',
  'owner_fullname': 'Муссова Оксана Сафарбиевна',
  'owner_birthday': '21.12.1979',
  'owner_doc_type': 'Паспорт',
  'owner_doc_series': '91 08',
  'owner_doc_number': '529244',
  'owner_addr_index': '350080',
  'owner_addr_federal': 'Россия, Краснодарский край',
  'owner_addr_district': '',
  'owner_addr_location': 'Краснодар',
  'owner_addr_street': 'Тюляева',
  'owner_addr_house': '25',
  'owner_addr_building': '',
  'owner_addr_apart': '90',
  'veh_category': 'B',
  'veh_model_mark': 'Hyundai Santa Fe Classic',
  'veh_id': 'X7MSC81DP8A008725',
  'veh_creation_year': '2008',
  'veh_engine_kw': '127.2',
  'veh_engine_force': '173',
  'veh_weight_limit': '2380',
  'veh_passengers': '',
  'veh_chassis': 'ОТСУТСТВУЕТ',
  'veh_body': 'X7MSC81DP8A008725',
  'veh_doc_type': 'ПТС',
  'veh_doc_series': '23 PB',
  'veh_doc_number': '104411',
  'veh_doc_date': '02.03.2019',
  'veh_reg_number': 'Е020ХА123',
  'y': true,
  'n': false,
  'p': true,
  's': false,
  't': false,
  'd': false,
  'r': false,
  'g': false,
  'h': false,
  'c': false,
  'o': false,
  'all': true,
  'only': false,
  'bt': 3000,
  'kt': 1.1,
  'kbm': 1.17,
  'kvs': 1.89,
  'ks': 1.0,
  'kp': 1.0,
  'km': 1.0,
  'ko': 2.32,
  'itg': (3000 * 1.1 * 1.17 * 1.89 * 2.32).toStringAsFixed(2),
};

Future<String?> fillTestOsago() async {
  return OsagoTemplate.fillOsago(testData);
}
